version: 1.0.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

artifacts:
  - path: dist\win\*.msi
    name: HandViewDesktop

deploy:
  release: v1.0.1
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: iSVmDGLvWisOvocYJIMvDZMpCb3s6MTTBryk9KPh/ZDLO8yMSl21U/uGFNmk4dKJ
  artifact: HandViewDesktop
  draft: false
  prerelease: false
  on:
    branch: v1.0.1
    appveyor_repo_tag: true        # deploy on tag push only

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g --silent
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist
  # HandView Setup 1.0.1.msi

test: off