version: 1.0.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

deploy:
  release: v1.0.0
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: iSVmDGLvWisOvocYJIMvDZMpCb3s6MTTBryk9KPh/ZDLO8yMSl21U/uGFNmk4dKJ
  artifact: /.*\.msi/ 
  draft: false
  prerelease: false
  on:
    branch: v1.0.0
    appveyor_repo_tag: true        # deploy on tag push only

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist
  - move dist\win-x64\Setup.msi dist\win-x64\HandView-$(appveyor_build_version).msi

test: off
